development: &default
  adapter: postgresql
  database: administrate-prototype_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
  username: postgres

test:
  <<: *default
  database: administrate-prototype_test
